blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<slug>', views.post_detail, name='post_detail'),
    path('<slug:slug>/like', views.post_like, name='post_like'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

STATIC_FILE_PATHS = static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

# handler404 = 'music.views.handler404'
# handler500 = 'music.views.handler500'

urlpatterns = [
    path('', include('music.urls')),
    path('account/', include('account.urls')),
    path('search/', include('search.urls')),
    path('blog/', include("blog.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('feedback/', include('feedback.urls')),
    path('admin/', admin.site.urls),

] + MEDIA_FILE_PATHS + STATIC_FILE_PATHS

music/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    # Uploads urls
    path('upload/album', views.create_album, name='upload_album'),
    path('upload/single', views.create_track, name='upload_single'),
    # Track urls
    path('track/<slug>', views.track_detail, name='track_detail'),
    path('track/<slug>/edit', views.edit_track, name='edit_track'),
    path('track/<slug>/favorite/', views.favorite_track, name='favorite_track'),
    path('track/<slug>/delete', views.delete_track, name='delete_track'),
    path('track/<slug:slug>/like', views.track_like, name='like_track'),

    # Album urls
    path('albums/', views.album_list, name='album_list'),
    path('album/<slug>', views.album_detail, name='album_detail'),
    path('album/<slug>/upload', views.create_track_album, name='add_to_album'),
    path('album/<slug>/edit', views.edit_album, name='edit_album'),
    path('album/<slug>/delete', views.delete_album, name='delete_album'),
    path('album/<slug>/favorite_album/', views.favorite_album, name='favorite_album'),


#     Playlist Urls
    path('playlists/', views.ManagePlaylistListView.as_view(), name='manage_playlist_list'),
    path('playlists/create/', views.PlaylistCreateView.as_view(), name='playlist_create'),
    path('playlists/<int:pk>/edit/', views.PlaylistUpdateView.as_view(), name='playlist_edit'),
    path('playlists/<int:pk>/delete/', views.PlaylistDeleteView.as_view(), name='playlist_delete'),
    path('playlist/add/<int:track>/<int:playlist>/', views.AddToPlaylist.as_view(), name='add_music_to_playlist'),
    path('playlist/remove/<int:track>/<int:playlist>/', views.RemoveFromPlaylist.as_view(),
         name='remove_music_from_playlist'),
    path('playlist/<slug:slug>/', views.PlaylistDetail.as_view(), name='playlist_detail'),
]

music/models.py
from uuid import uuid4

from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import Q
from django.urls import reverse
from tinymce import models as tinymyce_models
from django.utils.text import slugify

from feedback.models import Comment, Like


def media_directory_with_uuid(instance, filename):
    return '{}/{}'.format(instance.id, uuid4())


STATUS_CHOICES = (
        ('afrobeat', 'AfroBeat'),
        ('hip hop', 'Hip Hop'),
        ('r&b', 'R&B'),
        ('pop', 'Pop'),
        ('gospel', 'Gospel'),
        ('soul', 'Soul'),
        ('n/a', 'N/A')
    )

class AlbumQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (Q(title__icontains=query) |
                         Q(slug__icontains=query) |
                         Q(artist__username__icontains =query)
                         )
            qs = qs.filter(or_lookup).distinct()
        return qs

class AlbumManager(models.Manager):
    def get_queryset(self):
        return AlbumQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class Album(models.Model):
    title = models.CharField(max_length=100, null=False)
    slug = models.SlugField(max_length=100)
    released = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to=media_directory_with_uuid, blank=True)
    artist = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    genre = models.CharField(choices=STATUS_CHOICES, max_length=15, default='n/a')
    is_favorite = models.BooleanField(default=False)

    objects = AlbumManager()

    class Meta:
        ordering = ('released',)

    def __str__(self):
        return '{}'.format(self.title)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Album, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "album_detail",
            kwargs={
                "slug": self.slug
            }
        )

    def get_update_url(self):
        return reverse(
            "update_album",
            kwargs={
                "slug": self.slug
            }
        )

    def get_delete_url(self):
        return reverse(
            "delete_album",
            kwargs={
                "slug": self.slug
            }
        )

class Playlist(models.Model):
    name = models.CharField(max_length=100, help_text="Enter a name for your playlist")
    slug = models.SlugField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Playlist, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'playlist_detail',
            kwargs= {
                'slug': self.slug
            }
        )

    def __str__(self):
        return self.user.username

class MusicBase(models.Model):
    title = models.CharField(max_length=150, null=False)
    slug = models.SlugField(max_length=150)
    duration = models.PositiveIntegerField()

    class Meta:
        abstract = True
        ordering = ('title',)


class TrackQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (Q(title__icontains=query) |
                         Q(slug__icontains=query)
                         )
            qs = qs.filter(or_lookup).distinct()
        return qs

class TrackManager(models.Manager):
    def get_queryset(self):
        return TrackQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)

class Track(MusicBase):
    audio_file = models.FileField(upload_to=media_directory_with_uuid)
    released = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to=media_directory_with_uuid, blank=True)
    genre = models.CharField(choices=STATUS_CHOICES, max_length=15, default='n/a')
    artist = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True, blank=True)
    playlist = models.ManyToManyField(Playlist, blank=True) # related manager is track_set
    is_favorite = models.BooleanField(default=False)
    lyrics = tinymyce_models.HTMLField(null=True, blank=True)
    video_file = models.FileField(upload_to=media_directory_with_uuid, blank=True, null=True)

    objects = TrackManager()

    def __str__(self):
        return '{}'.format(self.title)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Track, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'track_detail',
            kwargs= {
                'slug': self.slug
            }
        )

    @property
    def likes(self):
        qs = Like.objects.filter_by_instance(self)
        return qs

    @property
    def get_content_type_like(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return content_type

    @property
    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs

    @property
    def get_content_type_comment(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return content_type

'''
 Not used. Changed my original design plan. 
 But you can remove the video_file attr from the Track class to use this video class
'''

#
# class Video(MusicBase):
#     file = models.FileField(upload_to='video/{}'.format(media_directory_with_uuid))
#     track = models.ForeignKey(Track, on_delete=models.DO_NOTHING, related_name='music_video')
#
#     def __str__(self):
#         return '{}'.format(self.track)
#
#     def save(self, *args, **kwargs):
#         if not self.slug:
#             self.slug = slugify(self.title)
#         super(Video, self).save(*args, **kwargs)

music/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Track, Album, Comment

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False

class AlbumForm(forms.ModelForm):
    artist = forms.HiddenInput(attrs={
        'name': 'artist',
        'required': False
    })

    class Meta:
        model = Album
        fields = ['title', 'thumbnail', 'genre']


class TrackForm(forms.ModelForm):
    lyrics = forms.CharField(widget=TinyMCE(
        mce_attrs={
            'required': False,
            'cols':30,
            'rows':10
        }, attrs={'required': True}
    ))
    album = forms.HiddenInput(attrs={
        'name': 'album',
        'required': False
    })

    class Meta:
        model = Track
        fields = ['title', 'duration', 'thumbnail', 'audio_file', 'video_file', 'genre', 'lyrics']

templates/music/playlist/playlist_create.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    {% if object %}
        Edit playlist "{{ object.name }}"
    {% else %}
        Create a Playlist
    {% endif %}
{% endblock %}

{% block content %}

    {% include 'sticky-left-side.html' %}

    {% include 'top_app_header.html' %}

    <div class="container">

        <div id="header" style="margin-top: 50px;">
            <div id="branding">
                <h1 class="form-title">
                    {% if object %}
                        <h1>Edit playlist "{{ object.name }}"</h1>
                    {% else %}
                        <h1>Create a Playlist</h1>
                    {% endif %}
                </h1>
            </div>
        </div>

        <div id="content" style="margin-bottom: 50px">
            <div id="content-main">
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form|crispy }}
{#                    <div class="form-row">#}
{#                        <label class="required" for="id_name">Name:</label>#}
{#                        <input type="text" name="name" autofocus maxlength="254" required id="id_name">#}
{#                        <p><small class="helptext">Enter a name for your playlist</small></p>#}
{#                    </div>#}
{#                    <div class="form-row">#}
{#                        <label class="required" for="id_slug">Slug:</label>#}
{#                        <input type="text" name="slug" maxlength="100" required id="id_slug">#}
{#                    </div>#}
                    <div class="submit-row">
                        <input type="submit" class="btn" value="Save playlist">
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}

{% endblock %}

templates/music/playlist/playlist_delete.html
{% extends "base.html" %}

{% block title %}Delete Playlist{% endblock %}

{% block content %}

    {% include 'sticky-left-side.html' %}

    {% include 'top_app_header.html' %}

    <h1>Delete Playlist"{{ object.name}}"</h1>
    <div class="module">
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" class="button" value="Confirm">
        </form>
    </div>

    {% include 'footer.html' %}
{% endblock %}

templates/music/playlist/playlist_detail.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <style>
        #playlist, audio{background:#666;width:400px;padding:20px;}
        .active a{color:#5DB0E6;text-decoration:none;}
        li a{color:#eeeedd;background:#333;padding:5px;display:block;}
        li a:hover{text-decoration:none;}
    </style>
{% endblock %}


{% block title %}
{{ playlist.name }}
{% endblock %}



{% block content %}

    {% include 'sticky-left-side.html' %}

    {% include 'top_app_header.html' %}

    <div class="container">
        <div class="row" style="margin: 50px 0">
            <h1>{{ playlist.name }}</h1>
            <ul id="playlist">
            {% for track in playlist.track_set.all %}
                <li style="list-style: decimal">
                    <a href="{{ track.audio_file.url }}" style="padding-right: 10px; border-right: 1px solid #f2f2f2;">{{ track }}</a>
                    <a href="{% url 'remove_music_from_playlist' track=track.id playlist=playlist.id %}" style="padding-left: 10px">remove</a>
                </li>
            {% endfor %}
            </ul>

            <hr>

            <script src="{% static 'js/playlist.js' %}" ></script>
            <button onclick="init()">Play Playlist</button>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

templates/music/playlist/playlist_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{{ request.user }}'s playlists
{% endblock %}

{% block content %}
    <div class="container">
        <h1>My Playlist</h1>
        <hr/>
        <ul>
        {% for playlist in object_list %}
            <li>
                <div>
                    <p>
                        <a class="" href="{% url 'playlist_detail' slug=playlist.slug%}">
                            <h3>{{ playlist.name }}</h3>
                        </a>
                    </p>
                    <p>created on {{ playlist.created_on }}</p>
                    <a class="" href="{% url 'playlist_delete' pk=playlist.id %}">delete</a>
                </div>
            </li>
        {% empty %}
            <li>No playlist have been created yet</li>
        {% endfor %}
        </ul>
        <a href="{% url 'playlist_create' %}">Create playlist</a>


        {#        {% include 'music/playlists/playlist_create.html' %}#}

    {#    <!-- Modal -->#}
    {##}
    {#    <div class="modal fade" id="myModal" role="dialog">#}
    {#        <div class="modal-dialog">#}
    {##}
    {#            <!-- Modal content-->#}
    {#            <div class="modal-content">#}
    {#                <div class="modal-header">#}
    {#                    <button type="button" class="close" data-dismiss="modal">&times;</button>#}
    {#                    <h4>Enter Playlist Name</h4>#}
    {#                </div>#}
    {#                <div class="modal-body">#}
    {#                    <form action="." method="post">#}
    {#                        <input type="text">#}
    {#                        {{ form.as_p }}#}
    {#                        {% csrf_token %}#}
    {#                        <p><input type="submit" value="Save playlist"></p>#}
    {#                    </form>#}
    {#                </div>#}
    {##}
    {#                <div class="modal-footer">#}
    {#                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    </div>

{% endblock %}